id = "helm"
name = "Helm"
version = "0.0.2"
schema_version = 1
authors = [
    "cabrinha <yuppie@hey.com>",
    "MrJosh <hi@mrjosh.me>",
    "Hemant Joshi <mail@hjoshi.me>",
]
description = "Syntax highlighting for Helm templates"
repository = "https://github.com/cabrinha/helm.zed"

[language_servers.helm]
name = "helm_ls"
language = "Helm"

[grammars.helm]
repository = "https://github.com/ngalaiko/tree-sitter-go-template"
commit = "9d3f6e526dd074b9edae9070b7bb778f00e87a5b"
path = "dialects/helm"
