#!/usr/bin/env bash
# Grammar pin / generated-files gate.
#
# 1. extension.toml [grammars.helm] commit must match tests/grammar-pin.sha
#    so the revision Zed downloads is the one queries are compiled against.
# 2. Prefer vendor/tree-sitter-helm in this checkout (the newline-after-{}
#    lexer). Clone the pin only if vendor/ is missing.
# 3. Like ngalaiko/tree-sitter-go-template CI: regenerate the helm dialect
#    and fail if committed parser artifacts drift (aside from the CLI
#    version banner in parser.c).
set -euo pipefail

# shellcheck source=lib/grammar-pin.sh
source "$(cd "$(dirname "$0")" && pwd)/lib/grammar-pin.sh"

load_grammar_pin
assert_grammar_pin_lock

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
ensure_tree_sitter "$WORK"

echo "Pin $GRAMMAR_REPO @$GRAMMAR_COMMIT ($GRAMMAR_PATH)"
echo "tree-sitter $(tree-sitter --version)"

stage_helm_grammar "$WORK/dialect"
echo "ok  grammar pin lock matches extension.toml and tests/grammar-pin.sha"

cd "$DIALECT"
git init -q
git add -A
git -c user.name=ci -c user.email=ci@helm.zed commit -qm pin
tree-sitter generate

# Ignore the "Automatically @generated by tree-sitter vX.Y.Z" banner so a
# patch CLI bump does not fail this gate. Real parser/node-types drift still
# fails, same as `git diff --exit-code` in the upstream grammar CI.
if ! git diff --exit-code \
  -I 'Automatically @generated by tree-sitter' \
  -- src; then
  echo "generated helm grammar artifacts drifted from git at $GRAMMAR_COMMIT" >&2
  echo "Bump the pin only to a commit whose $GRAMMAR_PATH/src is generated." >&2
  exit 1
fi

echo "ok  generated $GRAMMAR_PATH/src matches git (ignoring CLI version banner)"
echo "Grammar pin is consistent."
